# Setup
title:        Beatriz Borges R
tagline:      Passionate young computer scientist!
baseurl:      ""

# Blog-related
blog:
  title:   Learning from Nada (and Data)
  tagline: A Machine Learning blog

# About/contact
author:
  name:       Beatriz Borges R
  url:        http://obiwit.com

  email:      bea@obiwit.com
  github_username:        obiwit
  linkedin_username:      obiwit
  stackoverflow_username: 3059443/obiwit
  #twitter_username:
  #google_plus_username:
  #facebook_username:

# Gems
#plugins:
#  - jekyll-paginate

#Others
markdown: kramdown
