# Setup
title:        Beatriz Borges R
tagline:      Passionate young computer scientist!
description:  obiwit's personal website and machine learning blog
baseurl:      ""

# Blog-related
blog:
  title:   Learning from Nada (and Data)
  tagline: A Machine Learning blog
  posts:
    - title: Introduction
      url: index.html
    - title: Types of Learning
      url: types_learning.html
    - title: What is (Supervised) Machine Learning?
      url: what_is_ml.html

# About/contact
author:
  name:       Beatriz Borges R
  url:        http://obiwit.com

  email:      bea@obiwit.com
  github_username:        obiwit
  linkedin_username:      obiwit
  stackoverflow_username: 3059443/obiwit
  #kaggle_username:        obiwit
  #twitter_username:
  #google_plus_username:
  #facebook_username:

# Gems
plugins:
  - jekyll-seo-tag
  #  - jekyll-paginate

#Others
markdown: kramdown
