# Setup
title:        Beatriz Borges R
tagline:      Passionate young computer scientist!
baseurl:      ""
#paginate:     1

# About/contact
author:
  name:       Beatriz Borges R
  url:        http://obiwit.com

# Gems
#plugins:
#  - jekyll-paginate

#Others
markdown: kramdown
